import { UserProfile, Post, Opportunity, ConstructionProject, ChatThread, ChatMessage, AdCampaign, ModerationItem } from '../types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_curr',
  name: 'Eng. Roberto Silva',
  email: 'roberto.silva@alicerce.com.br',
  role: 'profissional_crea',
  avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
  bio: 'Especialista em Estruturas de Concreto Armado e Aço. Mais de 12 anos de experiência em edifícios residenciais e comerciais.',
  creaCauNumber: 'CREA-SP 5069824/D',
  verified: true,
  twoFactorEnabled: true,
  phone: '(11) 98765-4321',
  city: 'São Paulo',
  state: 'SP',
  specialties: ['Engenharia Estrutural', 'Cálculo de Fundações', 'Gerenciamento de Obras'],
  portfolioCount: 24,
  rating: 4.9,
  reviewsCount: 18,
  consentLgpd: true,
  createdAt: '2025-01-15',
};

export const MOCK_POSTS: Post[] = [
  {
    id: 'post_1',
    authorId: 'usr_camila',
    authorName: 'Engª. Camila Torres',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    authorRole: 'profissional_crea',
    authorBadge: 'Engenheira Estrutural • CREA-SP',
    category: 'obra_andamento',
    title: 'Concretagem de Laje Protendida - Edifício Horizon (14º Pavimento)',
    content: 'Concluímos hoje a concretagem de 450m² de laje protendida no Edifício Horizon. Utilizado fck 40 MPa com aditivo plastificante para garantia de fluidez e adensamento. Vistoria de armadura aprovada sem ressalvas.',
    mediaUrls: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    ],
    technicalStamp: {
      stampId: 'ALC-2026-8812',
      registrationNumber: 'CREA-SP 5092182/D',
      issueDate: '27/08/2026 09:15',
      hashVerification: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      artRrtCode: 'ART SP2026/998124',
      status: 'valid',
    },
    location: { city: 'São Paulo', state: 'SP' },
    budgetEstimated: 1250000,
    deadlineDays: 180,
    specialtyRequired: 'Estruturas de Concreto',
    likesCount: 142,
    commentsCount: 29,
    proposalsCount: 8,
    isLiked: true,
    createdAt: 'Há 2 horas',
  },
  {
    id: 'post_2',
    authorId: 'usr_horizon',
    authorName: 'Incorporadora & Construtora Horizon',
    authorAvatar: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop&q=80',
    authorRole: 'empresa_cnpj',
    authorBadge: 'Incorporadora • CNPJ Verificado',
    category: 'oportunidade',
    title: 'OPORTUNIDADE: Contratação de Empreiteira para Instalações Hidráulicas e de Incêndio',
    content: 'Estamos selecionando empresa ou equipe especializada para fornecimento e execução de instalações prediais de água fria, esgoto e prevenção de incêndio para novo condomínio residencial com 120 apartamentos em Campinas/SP.',
    mediaUrls: [
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=800&auto=format&fit=crop&q=80',
    ],
    technicalStamp: {
      stampId: 'ALC-2026-9041',
      registrationNumber: 'CNPJ 28.491.002/0001-84',
      issueDate: '27/08/2026 08:00',
      hashVerification: '8f4e2c91a0b3d5e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1',
      artRrtCode: 'CNPJ REGISTRO 2026-99',
      status: 'valid',
    },
    location: { city: 'Campinas', state: 'SP' },
    budgetEstimated: 480000,
    deadlineDays: 90,
    specialtyRequired: 'Instalações Hidráulicas & Incêndio',
    likesCount: 89,
    commentsCount: 15,
    proposalsCount: 12,
    isSponsored: true,
    createdAt: 'Há 4 horas',
  },
  {
    id: 'post_3',
    authorId: 'usr_lucas',
    authorName: 'Arq. Lucas Mendes',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    authorRole: 'profissional_cau',
    authorBadge: 'Arquiteto & Urbanista • CAU-BR',
    category: 'portfolio',
    title: 'Projeto Residencial Vila Nova - Arquitetura Bioclimática e Iluminação Natural',
    content: 'Apresentamos o conceito do projeto aprovado na Prefeitura de Curitiba. Estrutura mista de madeira engenheirada e aço, aproveitamento máximo de ventilação cruzada e captação de água pluvial para reuso.',
    mediaUrls: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop&q=80',
    ],
    technicalStamp: {
      stampId: 'ALC-2026-7734',
      registrationNumber: 'CAU A94812-3',
      issueDate: '26/08/2026 17:30',
      hashVerification: '7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b',
      artRrtCode: 'RRT CAU-PR 2026/4412',
      status: 'valid',
    },
    location: { city: 'Curitiba', state: 'PR' },
    likesCount: 215,
    commentsCount: 34,
    proposalsCount: 3,
    createdAt: 'Ontem',
  },
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp_1',
    title: 'Projeto Estrutural e Cálculo de Fundações para Galpão Logístico (4.000m²)',
    description: 'Necessitamos de engenheiro calculista para elaborar projeto executivo estrutural em pré-moldado de concreto e piso industrial de alta resistência para galpão comercial às margens da Rodovia Dutra.',
    category: 'Projeto Estrutural',
    specialty: 'Estruturas de Concreto / Metal',
    location: { city: 'Guarulhos', state: 'SP' },
    budgetRange: { min: 45000, max: 75000 },
    ownerId: 'usr_logistica',
    ownerName: 'ViaSul Logística Empreendimentos',
    ownerAvatar: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=150&auto=format&fit=crop&q=80',
    status: 'aberto',
    proposalsCount: 5,
    proposals: [
      {
        id: 'prop_101',
        opportunityId: 'opp_1',
        proposerId: 'usr_curr',
        proposerName: 'Eng. Roberto Silva',
        proposerRole: 'profissional_crea',
        proposerAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
        creaCau: 'CREA-SP 5069824/D',
        value: 58000,
        deadlineDays: 25,
        scopeDescription: 'Inclusos: Modelagem BIM em Revit, dimensionamento de pilares e vigas pré-moldadas, verificação de solo para estacas escavadas, relatório descritivo e ART inclusa.',
        attachmentUrl: 'Proposta_Tecnica_Galpao_RobertoSilva.pdf',
        status: 'em_negociacao',
        createdAt: 'Há 1 dia',
      },
      {
        id: 'prop_102',
        opportunityId: 'opp_1',
        proposerId: 'usr_marcos',
        proposerName: 'Eng. Marcos Vinicius',
        proposerRole: 'profissional_crea',
        proposerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        creaCau: 'CREA-RJ 120491/D',
        value: 62000,
        deadlineDays: 20,
        scopeDescription: 'Projeto completo com simulação de cargas dinâmicas e detalhamento de juntas de dilatação do piso.',
        status: 'pendente',
        createdAt: 'Há 2 dias',
      },
    ],
    createdAt: 'Há 3 dias',
  },
  {
    id: 'opp_2',
    title: 'Laudo de Estabilidade Estrutural e Reforma de Fachada de Prédio Histórico',
    description: 'Contratação de engenheiro ou arquiteto especialista em restauração para laudo técnico de marquise e fachada de edifício na área central de Porto Alegre.',
    category: 'Laudos e Perícias',
    specialty: 'Perícias e Restauração',
    location: { city: 'Porto Alegre', state: 'RS' },
    budgetRange: { min: 20000, max: 35000 },
    ownerId: 'usr_condominio',
    ownerName: 'Condomínio Edifício União',
    ownerAvatar: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=150&auto=format&fit=crop&q=80',
    status: 'aberto',
    proposalsCount: 3,
    proposals: [],
    createdAt: 'Há 1 dia',
  },
];

export const MOCK_PROJECTS: ConstructionProject[] = [
  {
    id: 'proj_1',
    title: 'Residencial Jardins das Orquídeas',
    location: 'São Paulo - SP (Vila Madalena)',
    totalBudget: 4200000,
    overallProgress: 68,
    responsavelTecnico: 'Engª. Camila Torres',
    creaNumber: 'CREA-SP 5092182/D',
    milestones: [
      {
        id: 'm1',
        phase: 'Fundação e Terraplanagem',
        progressPercent: 100,
        title: 'Estacamento Hélice Contínua e Bloco de Coronamento',
        description: 'Execução de 42 estacas hélice com profundidade média de 16m. Testes de integridade (PIT) 100% conformes.',
        photoUrls: ['https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?w=600&auto=format&fit=crop&q=80'],
        costIncurred: 650000,
        updatedAt: '12/03/2026',
        responsibleCrea: 'CREA-SP 5092182/D',
      },
      {
        id: 'm2',
        phase: 'Estrutura e Concreto',
        progressPercent: 100,
        title: 'Conclusão do 10º Pavimento de Concreto Armado',
        description: 'Estrutura finalizada dentro do cronograma físico-financeiro.',
        photoUrls: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80'],
        costIncurred: 1800000,
        updatedAt: '15/06/2026',
        responsibleCrea: 'CREA-SP 5092182/D',
      },
      {
        id: 'm3',
        phase: 'Alvenaria e Vedações',
        progressPercent: 85,
        title: 'Assentamento de Blocos Cerâmicos e Vergas',
        description: 'Pavimentos de 1 a 8 concluídos. Em andamento pavimentos 9 e 10.',
        photoUrls: ['https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=600&auto=format&fit=crop&q=80'],
        costIncurred: 420000,
        updatedAt: '20/08/2026',
        responsibleCrea: 'CREA-SP 5092182/D',
      },
      {
        id: 'm4',
        phase: 'Instalações Elétricas e Hidráulicas',
        progressPercent: 40,
        title: 'Passagem de Tubulação e Infraestrutura de Ar Condicionado',
        description: 'Tubulação PPR de água quente e prumadas de esgoto em execução.',
        photoUrls: ['https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=600&auto=format&fit=crop&q=80'],
        costIncurred: 280000,
        updatedAt: '25/08/2026',
        responsibleCrea: 'CREA-SP 5092182/D',
      },
    ],
  },
];

export const MOCK_CHAT_THREADS: ChatThread[] = [
  {
    id: 'thread_1',
    participantId: 'usr_camila',
    participantName: 'Engª. Camila Torres',
    participantAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    participantRole: 'Engenheira Estrutural • CREA-SP',
    lastMessage: 'Enviei a ART atualizada da laje do 14º andar em PDF.',
    lastMessageTime: '09:30',
    unreadCount: 1,
  },
  {
    id: 'thread_2',
    participantId: 'usr_logistica',
    participantName: 'ViaSul Logística Empreendimentos',
    participantAvatar: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=150&auto=format&fit=crop&q=80',
    participantRole: 'Contratante • CNPJ Verificado',
    lastMessage: 'Analisamos sua proposta para o galpão em Guarulhos. Podemos agendar uma reunião?',
    lastMessageTime: 'Ontem',
    unreadCount: 0,
  },
];

export const MOCK_MESSAGES: Record<string, ChatMessage[]> = {
  thread_1: [
    {
      id: 'm1',
      senderId: 'usr_camila',
      senderName: 'Engª. Camila Torres',
      receiverId: 'usr_curr',
      text: 'Olá Roberto, tudo bem? Vi sua publicação sobre o cálculo de concreto protendido.',
      timestamp: '09:15',
      read: true,
    },
    {
      id: 'm2',
      senderId: 'usr_curr',
      senderName: 'Eng. Roberto Silva',
      receiverId: 'usr_camila',
      text: 'Olá Camila! Excelente o resultado da concretagem da laje do Edifício Horizon.',
      timestamp: '09:22',
      read: true,
    },
    {
      id: 'm3',
      senderId: 'usr_camila',
      senderName: 'Engª. Camila Torres',
      receiverId: 'usr_curr',
      text: 'Enviei a ART atualizada da laje do 14º andar em PDF.',
      attachmentUrl: 'ART_LajeProtendida_CamilaTorres.pdf',
      timestamp: '09:30',
      read: false,
    },
  ],
};

export const MOCK_CAMPAIGNS: AdCampaign[] = [
  {
    id: 'camp_1',
    userId: 'usr_curr',
    title: 'Destaque de Perfil Profissional - Engenharia Estrutural SP',
    objective: 'Captação de Leads',
    targetAudience: ['Engenheiros', 'Construtoras', 'Incorporadoras'],
    targetRegion: 'São Paulo e Grande SP',
    dailyBudget: 50,
    totalBudget: 700,
    durationDays: 14,
    impressionsCount: 14200,
    clicksCount: 480,
    status: 'ativa',
    paymentMethod: 'pix',
    invoiceNfseUrl: 'NFS-e_ALICERCE_009812.pdf',
    createdAt: '20/08/2026',
  },
];

export const MOCK_MODERATION: ModerationItem[] = [
  {
    id: 'mod_1',
    type: 'post',
    targetId: 'post_spm_9',
    title: 'Serviço de Reforma Rápida Sem Registro',
    authorName: 'Usuário Não Verificado',
    reason: 'Falta de Registro Técnico CREA/CAU obrigatorio em anúncio de obra de porte.',
    reportsCount: 4,
    status: 'pendente',
    createdAt: '27/08/2026 07:12',
  },
];
